// Generated by scripts/check_selectors.py from protocol/abi.json and vectors.json.
// Independently checked by the pinned Cairo selector! macro; no Python hash is used here.

#[test]
fn test_frozen_selectors() {
    let expected = 118392661602862932221173705796653290549413119731538510511556647074259381935;
    assert(selector!("link") == expected, 'SELECTOR_MISMATCH');
    let expected = 1006914996534709224607738575252571802087119588540572262759330458818632830651;
    assert(selector!("move") == expected, 'SELECTOR_MISMATCH');
    let expected = 924721843728457642046450709855086375553246761384863197579636433244766369444;
    assert(selector!("unlink") == expected, 'SELECTOR_MISMATCH');
    let expected = 934512645634985500479763787408240173630153827023378265377072214039549757247;
    assert(selector!("revoke") == expected, 'SELECTOR_MISMATCH');
    let expected = 33530722123114163495537150410121452060380698766397091934058216439154184856;
    assert(selector!("invalidate_pending_incoming") == expected, 'SELECTOR_MISMATCH');
    let expected = 1763025929211227335853106994442683518102415950229763973581974164746276287439;
    assert(selector!("get_starknet_address") == expected, 'SELECTOR_MISMATCH');
    let expected = 1550129227972480089764567780430461156649644375074562450098094002593794782188;
    assert(selector!("is_associated") == expected, 'SELECTOR_MISMATCH');
    let expected = 119525126747277903035077534463079406790978013832681419985683213840258428872;
    assert(selector!("get_ethereum_address_count") == expected, 'SELECTOR_MISMATCH');
    let expected = 847580314827042002708687469511297426327441163202455403382953054207758704318;
    assert(selector!("get_ethereum_addresses") == expected, 'SELECTOR_MISMATCH');
    let expected = 1651012852140321144845563424212074052338616280820763327347463283046840910810;
    assert(selector!("get_ethereum_nonce") == expected, 'SELECTOR_MISMATCH');
    let expected = 1411271411174963294134752208050788656180805291236005239697281541178194707216;
    assert(selector!("get_recipient_nonce") == expected, 'SELECTOR_MISMATCH');
    let expected = 1310545266356131638114812250512503835193636519109619794471606666222973028642;
    assert(selector!("get_signing_domain") == expected, 'SELECTOR_MISMATCH');
    let expected = 1195681022256312569485265215678921889486245873266906069896048805207026720683;
    assert(selector!("get_version") == expected, 'SELECTOR_MISMATCH');
    let expected = 1159040026212278395030414237414753050475174923702621880048416706425641521556;
    assert(selector!("constructor") == expected, 'SELECTOR_MISMATCH');
    let expected = 1213293078385536787199108047425788666059335243598577587069513353622615676613;
    assert(selector!("AssociationChanged") == expected, 'SELECTOR_MISMATCH');
    let expected = 988009767576052647314861782225598850481172693862110282949715272835855761435;
    assert(selector!("EthereumNonceAdvanced") == expected, 'SELECTOR_MISMATCH');
    let expected = 858446140938378784240430741772175703523500764517914556554214632816048963719;
    assert(selector!("RecipientNonceAdvanced") == expected, 'SELECTOR_MISMATCH');
}
