[package]
name = "contracts"
version = "0.1.0"
edition = "2024_07"
cairo-version = "=2.20.0"
publish = false

[dependencies]
starknet = "=2.20.0"

[dev-dependencies]
snforge_std = "=0.64.0"

[[target.starknet-contract]]
sierra = true

[cairo]
allow-warnings = false

[scripts]
test = "snforge test"

[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]

[tool.snforge]
fuzzer_runs = 256

[profile.coverage]
inherits = "dev"

[profile.coverage.cairo]
unstable-add-statements-code-locations-debug-info = true
unstable-add-statements-functions-debug-info = true
inlining-strategy = "avoid"
