#!/usr/bin/env python3
"""Generate/check a Cairo selector! test directly from the frozen ABI and vectors."""
import argparse
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
TARGET = "contracts/tests/test_selectors.cairo"


def selector_cases(abi, vectors):
    methods = [item["name"] for entry in abi for item in
               (entry.get("items", []) if entry["type"] == "interface" else [entry])
               if item["type"] in {"function", "constructor"}]
    if set(vectors["selectors"]) != set(methods):
        raise ValueError("Frozen selector inventory differs from compiler ABI")
    cases = dict(vectors["selectors"])
    root_event = next(entry for entry in abi if entry.get("name") ==
                      "contracts::registry::EthereumAddressAssociationRegistry::Event")
    event_names = {variant["name"] for variant in root_event["variants"]}
    events = {}
    for vector in [*vectors["vectors"], *vectors["unsigned_vectors"]]:
        call = vector.get("calldata") if "typed_data" in vector else vector
        if call["selector"] != cases.get(call["entrypoint"]):
            raise ValueError("Fixture call selector differs from frozen selector table")
        for event in vector["expected"]["events"]:
            name, value = event["name"], event["keys"][0]
            if name not in event_names or (name in events and events[name] != value):
                raise ValueError("Fixture event selectors are inconsistent with the ABI inventory")
            events[name] = value
    if set(events) != event_names:
        raise ValueError("Frozen fixtures omit an ABI event selector")
    cases.update(events)
    for name, value in cases.items():
        if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", name):
            raise ValueError("Unsafe selector name")
        if not isinstance(value, str) or not re.fullmatch(r"[0-9]+", value) or not 0 <= int(value) < 2**250:
            raise ValueError("Invalid frozen selector value")
    return cases


def source(abi, vectors):
    cases = selector_cases(abi, vectors)
    return ("// Generated by scripts/check_selectors.py from protocol/abi.json and vectors.json.\n"
            "// Independently checked by the pinned Cairo selector! macro; no Python hash is used here.\n"
            "\n#[test]\nfn test_frozen_selectors() {\n"
            + "".join(f'    let expected = {value};\n    assert(selector!("{name}") == expected, \'SELECTOR_MISMATCH\');\n' for name, value in cases.items())
            + "}\n")


def check(write=False):
    expected = source(json.loads((ROOT / "protocol/abi.json").read_text()),
                      json.loads((ROOT / "protocol/vectors.json").read_text()))
    path = ROOT / TARGET
    if write:
        path.write_text(expected)
    elif not path.is_file() or path.read_text() != expected:
        raise ValueError("Generated Cairo selector test differs from frozen artifacts")
    print("Artifact-driven Cairo selector test is current")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true")
    check(parser.parse_args().write)
